name: Test runner
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Restore packages
      run: |
        dotnet test --logger trx

    - name: Upload test results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: TestResults